export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_USER = 'ADD_USER';
export const GET_USERS = 'GET_USERS';
export const USER_ERROR = 'USER_ERROR';

export const USERS_LOADING = 'GET_USERS_LOADING';
export const CLEAR_USERS_ERROR = 'CLEAR_USERS_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

export const GET_ARTICLE = 'GET_ARTICLE';

export const FETCH_FEED_START = 'FETCH_FEED_START';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
export const FETCH_FEED_FAIL = 'FETCH_FEED_FAIL';


